spring:
  config:
    activate:
      on-profile: "local"

server:
  port: 9000
  servlet:
    session:
      timeout: 5000


management:
  endpoint:
    logfile:
      external-file: ~/logback.log
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,loggers,metrics,mappings,threaddump,conditions,info,heapdump
      base-path: /api/actuator
      path-mapping:
        loggers: logs
        httptrace: trace


slack:
  api:
    token: YOUR_SLACK_API_TOKEN
    signingSecret: YOUR_SIGNING_SECRET
  app:
    token: YOUR_SLACK_APP_TOKEN