spring:
  config:
    activate:
      on-profile: "prod"

  lifecycle:
    timeout-per-shutdown-phase: 10s

  threads:
    virtual:
      enabled: true

  datasource:
    hikari:
      transaction-isolation: ${SQL_PROD_ISOLATION_LEVEL}
      maximum-pool-size: 10
#      minimum-idle: 10
      connection-timeout: ${SQL_PROD_CONNECTION_TIMEOUT}
      validation-timeout: ${SQL_PROD_VALIDATION_TIMEOUT}
      connection-test-query: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: hikari_pool

    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SQL_DATABASE_URL}
    username: ${SQL_DATABASE_USERNAME}
    password: ${SQL_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: ${HIBERNATE_DEFAULT_BATCH_SIZE}
    generate-ddl: false
  h2:
    console:
      enabled: false

  kafka:
    bootstrap-servers: [ "kafka:port" ]
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: codeCompanion
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
      max-poll-records: 1000
      isolation-level: read_committed

server:
  port: 80
  servlet:
    session:
      timeout: 5000
  shutdown: graceful

management:
  endpoint:
    logfile:
      external-file: ./logback.log
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health,loggers,metrics,mappings,threaddump,conditions,info,heapdump
      base-path: ${ACTUATOR_BASE_PATH}
      path-mapping:
        loggers: logs
        httptrace: trace

slack:
  app:
    api:
      token: ${SLACK_API_TOKEN}
    mode:
      publisher: cdc
      cdc:
        topic: cdc.code_companion.outbox_message