apiVersion: v1
kind: Service
metadata:
  name: code-companion-svc
spec:
  ports:
    - name: code-companion-svc
      port: 80
      targetPort: 80
  selector:
    app: code-companion-deploy
  type: ClusterIP